### ISSUE TITLE
Чеклист проверок по лаб 3

### ISSUE THREAD

**Issue by moleus** [moleus/highload-systems-itmo#184]
- [x] запустить в докере, через api-gateway отправить запросы из requests
- [x] отключить кафку и посмотреть что будут делать приложения
- [x] отключить minio и посмотреть какой ответ получит пользователь
- [x] запустить в докере и проверить, что по вебсокетам отправляется нотификации (Ева проверяла и я тоже, но стоит еще разок)
- [x] запустить кластер из 3х кафок и проверить, что репликация топиков и сообщений работает. https://github.com/moleus/highload-systems-itmo/issues/183
   - [x] нужно у приложений в енве KAFKA_HOST прописать 3 ендпоинта кафок. - kafka-1:9000,kafka-2:9000,kafka-3:9000
   - [x] проверить, что если одна кафка умерла, работа продолжается
- [x] #185
- [x] Проверить работоспособность feign client в image_service в docker
- [x] Проверить недоступность Image service не через animal service, насколько помню, он у нас доступен, хотя хотелось бы, чтобы к нему был доступ только через animal

**Comment by Korako2** [comment]
Лаба сдана
