### ISSUE TITLE
Не работает фильтрация по `api/v1/transactions/expenses?purposeID=1`

### ISSUE THREAD

**Issue by moleus** [moleus/highload-systems-itmo#263]
<img width="1170" alt="image" src="https://github.com/user-attachments/assets/f2dd672f-510b-49e8-8f22-d76f3b5363ae">

```
GET http://highload.duckdns.org/api/v1/transactions/expenses?purposeID=1
```

**Comment by Korako2** [comment]
Исправлено.

Для Ильи Владимировича: 
не проверяйте, пожалуйста 😩
